In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [ ]:
df=pd.read_csv("blogs.csv")
df

                                                   Data              Labels
0     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
1     Newsgroups: alt.atheism\nPath: cantaloupe.srv....         alt.atheism
2     Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...         alt.atheism
3     Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...         alt.atheism
4     Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...         alt.atheism
...                                                 ...                 ...
1995  Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...  talk.religion.misc
1996  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1997  Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...  talk.religion.misc
1998  Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  talk.religion.misc
1999  Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...  talk.religion.misc

[2000 rows x 2 columns]

In [ ]:
#Data Exploration and preprocessing

In [ ]:
len(df)

2000

In [ ]:
df.shape

(2000, 2)

In [ ]:
df.dtypes

Data      object
Labels    object
dtype: object

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Data    2000 non-null   object
 1   Labels  2000 non-null   object
dtypes: object(2)
memory usage: 31.4+ KB

In [ ]:
df.describe()

                                                     Data       Labels
count                                                2000         2000
unique                                               2000           20
top     Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  alt.atheism
freq                                                    1          100

In [ ]:
df.describe()

                                                     Data       Labels
count                                                2000         2000
unique                                               2000           20
top     Xref: cantaloupe.srv.cs.cmu.edu talk.religion....  alt.atheism
freq                                                    1          100

In [ ]:
df["Labels"].unique()

array(['alt.atheism', 'comp.graphics', 'comp.os.ms-windows.misc',
       'comp.sys.ibm.pc.hardware', 'comp.sys.mac.hardware',
       'comp.windows.x', 'misc.forsale', 'rec.autos', 'rec.motorcycles',
       'rec.sport.baseball', 'rec.sport.hockey', 'sci.crypt',
       'sci.electronics', 'sci.med', 'sci.space',
       'soc.religion.christian', 'talk.politics.guns',
       'talk.politics.mideast', 'talk.politics.misc',
       'talk.religion.misc'], dtype=object)

In [ ]:
df["Labels"].value_counts()

Labels
alt.atheism                 100
comp.graphics               100
comp.os.ms-windows.misc     100
comp.sys.ibm.pc.hardware    100
comp.sys.mac.hardware       100
comp.windows.x              100
misc.forsale                100
rec.autos                   100
rec.motorcycles             100
rec.sport.baseball          100
rec.sport.hockey            100
sci.crypt                   100
sci.electronics             100
sci.med                     100
sci.space                   100
soc.religion.christian      100
talk.politics.guns          100
talk.politics.mideast       100
talk.politics.misc          100
talk.religion.misc          100
Name: count, dtype: int64

In [ ]:
df["Data"].str.len().describe()

count     2000.000000
mean      2324.978000
std       3590.560226
min        425.000000
25%       1147.000000
50%       1605.500000
75%       2374.500000
max      62290.000000
Name: Data, dtype: float64

In [ ]:
df.isnull().sum()

Data      0
Labels    0
dtype: int64

In [ ]:
import re
def clean_text(text):
  text = re.sub(r'[^a-zA-Z\s]', '', text)    #Remove special characters and punctuation
  text = text.lower() # Convert to lowercase
  text = text.strip()  #Remove leading and trailing whitespace
  return text
df['cleaned'] = df['Data'].apply(clean_text)
df

,Data,Labels,cleaned
0,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...
1,Newsgroups: alt.atheism\nPath: cantaloupe.srv....,alt.atheism,newsgroups altatheism\npath cantaloupesrvcscmu...
2,Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...,alt.atheism,path cantaloupesrvcscmuedudasnewsharvardedunoc...
3,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...
4,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...,alt.atheism,xref cantaloupesrvcscmuedu altatheism talkreli...
...,...,...,...
1995,Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...,talk.religion.misc,xref cantaloupesrvcscmuedu talkabortion altath...
1996,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc ta...
1997,Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...,talk.religion.misc,xref cantaloupesrvcscmuedu talkorigins talkrel...
1998,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc al...
1999,Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...,talk.religion.misc,xref cantaloupesrvcscmuedu sciskeptic talkpoli...

In [33]:
!pip install nltk

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.1)

In [36]:
#tokenization:
#Tokenize the cleaned text data and store the tokens in a new column

from nltk.tokenize import word_tokenize
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

def tokenize_text(text):
  return word_tokenize(text)

df['tokens'] = df['cleaned'].apply(tokenize_text)
df

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

,Data,Labels,cleaned,tokens
0,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...,"[path, cantaloupesrvcscmuedumagnesiumclubcccmu..."
1,Newsgroups: alt.atheism\nPath: cantaloupe.srv....,alt.atheism,newsgroups altatheism\npath cantaloupesrvcscmu...,"[newsgroups, altatheism, path, cantaloupesrvcs..."
2,Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...,alt.atheism,path cantaloupesrvcscmuedudasnewsharvardedunoc...,"[path, cantaloupesrvcscmuedudasnewsharvardedun..."
3,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...,"[path, cantaloupesrvcscmuedumagnesiumclubcccmu..."
4,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...,alt.atheism,xref cantaloupesrvcscmuedu altatheism talkreli...,"[xref, cantaloupesrvcscmuedu, altatheism, talk..."
...,...,...,...,...
1995,Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...,talk.religion.misc,xref cantaloupesrvcscmuedu talkabortion altath...,"[xref, cantaloupesrvcscmuedu, talkabortion, al..."
1996,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc ta...,"[xref, cantaloupesrvcscmuedu, talkreligionmisc..."
1997,Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...,talk.religion.misc,xref cantaloupesrvcscmuedu talkorigins talkrel...,"[xref, cantaloupesrvcscmuedu, talkorigins, tal..."
1998,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc al...,"[xref, cantaloupesrvcscmuedu, talkreligionmisc..."
1999,Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...,talk.religion.misc,xref cantaloupesrvcscmuedu sciskeptic talkpoli...,"[xref, cantaloupesrvcscmuedu, sciskeptic, talk..."

In [37]:
#Stop words
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
def remove_stopwords(tokens):
    return [word for word in tokens if word not in stop_words]

df['tokens_no_stopwords'] = df['tokens'].apply(remove_stopwords)
df

,Data,Labels,cleaned,tokens,tokens_no_stopwords
0,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...,"[path, cantaloupesrvcscmuedumagnesiumclubcccmu...","[path, cantaloupesrvcscmuedumagnesiumclubcccmu..."
1,Newsgroups: alt.atheism\nPath: cantaloupe.srv....,alt.atheism,newsgroups altatheism\npath cantaloupesrvcscmu...,"[newsgroups, altatheism, path, cantaloupesrvcs...","[newsgroups, altatheism, path, cantaloupesrvcs..."
2,Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...,alt.atheism,path cantaloupesrvcscmuedudasnewsharvardedunoc...,"[path, cantaloupesrvcscmuedudasnewsharvardedun...","[path, cantaloupesrvcscmuedudasnewsharvardedun..."
3,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...,"[path, cantaloupesrvcscmuedumagnesiumclubcccmu...","[path, cantaloupesrvcscmuedumagnesiumclubcccmu..."
4,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...,alt.atheism,xref cantaloupesrvcscmuedu altatheism talkreli...,"[xref, cantaloupesrvcscmuedu, altatheism, talk...","[xref, cantaloupesrvcscmuedu, altatheism, talk..."
...,...,...,...,...,...
1995,Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...,talk.religion.misc,xref cantaloupesrvcscmuedu talkabortion altath...,"[xref, cantaloupesrvcscmuedu, talkabortion, al...","[xref, cantaloupesrvcscmuedu, talkabortion, al..."
1996,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc ta...,"[xref, cantaloupesrvcscmuedu, talkreligionmisc...","[xref, cantaloupesrvcscmuedu, talkreligionmisc..."
1997,Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...,talk.religion.misc,xref cantaloupesrvcscmuedu talkorigins talkrel...,"[xref, cantaloupesrvcscmuedu, talkorigins, tal...","[xref, cantaloupesrvcscmuedu, talkorigins, tal..."
1998,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc al...,"[xref, cantaloupesrvcscmuedu, talkreligionmisc...","[xref, cantaloupesrvcscmuedu, talkreligionmisc..."
1999,Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...,talk.religion.misc,xref cantaloupesrvcscmuedu sciskeptic talkpoli...,"[xref, cantaloupesrvcscmuedu, sciskeptic, talk...","[xref, cantaloupesrvcscmuedu, sciskeptic, talk..."

In [53]:
# Lemmatization
from nltk.stem import WordNetLemmatizer
from nltk.corpus import wordnet
lemmatizer = WordNetLemmatizer()
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [54]:
lemmatizer = WordNetLemmatizer()

def get_wordnet_pos(word):
    """Map POS tag to first character used by WordNetLemmatizer"""
    tag = nltk.pos_tag([word])[0][1][0].upper()
    tag_dict = {"N": wordnet.NOUN,
                "V": wordnet.VERB,
                "A": wordnet.ADJ,
                "R": wordnet.ADV}
    return tag_dict.get(tag, wordnet.NOUN)

def lemmatize_tokens(tokens):
    return [lemmatizer.lemmatize(token, get_wordnet_pos(token)) for token in tokens]

df['lemmatized_tokens'] = df['tokens_no_stopwords'].apply(lemmatize_tokens)
df

,Data,Labels,cleaned,tokens,tokens_no_stopwords,lemmatized_tokens
0,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...,"[path, cantaloupesrvcscmuedumagnesiumclubcccmu...","[path, cantaloupesrvcscmuedumagnesiumclubcccmu...","[path, cantaloupesrvcscmuedumagnesiumclubcccmu..."
1,Newsgroups: alt.atheism\nPath: cantaloupe.srv....,alt.atheism,newsgroups altatheism\npath cantaloupesrvcscmu...,"[newsgroups, altatheism, path, cantaloupesrvcs...","[newsgroups, altatheism, path, cantaloupesrvcs...","[newsgroups, altatheism, path, cantaloupesrvcs..."
2,Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...,alt.atheism,path cantaloupesrvcscmuedudasnewsharvardedunoc...,"[path, cantaloupesrvcscmuedudasnewsharvardedun...","[path, cantaloupesrvcscmuedudasnewsharvardedun...","[path, cantaloupesrvcscmuedudasnewsharvardedun..."
3,Path: cantaloupe.srv.cs.cmu.edu!magnesium.club...,alt.atheism,path cantaloupesrvcscmuedumagnesiumclubcccmued...,"[path, cantaloupesrvcscmuedumagnesiumclubcccmu...","[path, cantaloupesrvcscmuedumagnesiumclubcccmu...","[path, cantaloupesrvcscmuedumagnesiumclubcccmu..."
4,Xref: cantaloupe.srv.cs.cmu.edu alt.atheism:53...,alt.atheism,xref cantaloupesrvcscmuedu altatheism talkreli...,"[xref, cantaloupesrvcscmuedu, altatheism, talk...","[xref, cantaloupesrvcscmuedu, altatheism, talk...","[xref, cantaloupesrvcscmuedu, altatheism, talk..."
...,...,...,...,...,...,...
1995,Xref: cantaloupe.srv.cs.cmu.edu talk.abortion:...,talk.religion.misc,xref cantaloupesrvcscmuedu talkabortion altath...,"[xref, cantaloupesrvcscmuedu, talkabortion, al...","[xref, cantaloupesrvcscmuedu, talkabortion, al...","[xref, cantaloupesrvcscmuedu, talkabortion, al..."
1996,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc ta...,"[xref, cantaloupesrvcscmuedu, talkreligionmisc...","[xref, cantaloupesrvcscmuedu, talkreligionmisc...","[xref, cantaloupesrvcscmuedu, talkreligionmisc..."
1997,Xref: cantaloupe.srv.cs.cmu.edu talk.origins:4...,talk.religion.misc,xref cantaloupesrvcscmuedu talkorigins talkrel...,"[xref, cantaloupesrvcscmuedu, talkorigins, tal...","[xref, cantaloupesrvcscmuedu, talkorigins, tal...","[xref, cantaloupesrvcscmuedu, talkorigins, tal..."
1998,Xref: cantaloupe.srv.cs.cmu.edu talk.religion....,talk.religion.misc,xref cantaloupesrvcscmuedu talkreligionmisc al...,"[xref, cantaloupesrvcscmuedu, talkreligionmisc...","[xref, cantaloupesrvcscmuedu, talkreligionmisc...","[xref, cantaloupesrvcscmuedu, talkreligionmisc..."
1999,Xref: cantaloupe.srv.cs.cmu.edu sci.skeptic:43...,talk.religion.misc,xref cantaloupesrvcscmuedu sciskeptic talkpoli...,"[xref, cantaloupesrvcscmuedu, sciskeptic, talk...","[xref, cantaloupesrvcscmuedu, sciskeptic, talk...","[xref, cantaloupesrvcscmuedu, sciskeptic, talk..."

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
x=vectorizer.fit_transform(df["cleaned"])
y=df["Labels"]

In [57]:
#Naive Bayes Model For Text Classification

In [58]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report

In [59]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42,stratify=y)

In [60]:
nb=MultinomialNB()
nb.fit(X_train,Y_train)
y_pred=nb.predict(X_test)

In [62]:
print("Accuracy:",accuracy_score(Y_test, y_pred))
print("Precision:",precision_score(Y_test, y_pred, average="macro", zero_division=0))
print("Recall:",recall_score(Y_test, y_pred, average="macro", zero_division=0))
print("F1-score:",f1_score(Y_test, y_pred, average="macro", zero_division=0))
print("Classification Report:",classification_report(Y_test, y_pred,zero_division=0))

Accuracy: 0.7675
Precision: 0.8165069652875566
Recall: 0.7675000000000001
F1-score: 0.7743188945477756
Classification Report:                           precision    recall  f1-score   support

             alt.atheism       0.75      0.60      0.67        20
           comp.graphics       0.86      0.60      0.71        20
 comp.os.ms-windows.misc       0.89      0.80      0.84        20
comp.sys.ibm.pc.hardware       0.62      0.75      0.68        20
   comp.sys.mac.hardware       0.87      0.65      0.74        20
          comp.windows.x       0.94      0.75      0.83        20
            misc.forsale       1.00      0.60      0.75        20
               rec.autos       0.92      0.60      0.73        20
         rec.motorcycles       1.00      0.75      0.86        20
      rec.sport.baseball       0.95      0.95      0.95        20
        rec.sport.hockey       0.95      0.95      0.95        20
               sci.crypt       0.69      1.00      0.82        20
         sci.electronics       0.82      0.70      0.76        20
                 sci.med       0.94      0.80      0.86        20
               sci.space       0.94      0.85      0.89        20
  soc.religion.christian       0.43      1.00      0.61        20
      talk.politics.guns       0.72      0.65      0.68        20
   talk.politics.mideast       0.80      1.00      0.89        20
      talk.politics.misc       0.78      0.70      0.74        20
      talk.religion.misc       0.45      0.65      0.53        20

                accuracy                           0.77       400
               macro avg       0.82      0.77      0.77       400
            weighted avg       0.82      0.77      0.77       400

In [63]:
!pip install textblob

Requirement already satisfied: textblob in /usr/local/lib/python3.12/dist-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in /usr/local/lib/python3.12/dist-packages (from textblob) (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (1.5.2)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (2024.11.6)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk>=3.9->textblob) (4.67.1)

In [64]:
from textblob import TextBlob

def get_sentiment(text):
  polarity = TextBlob(str(text)).polarity
  if polarity > 0.1:
    return "positive"
  elif polarity < -0.1:
    return "negative"
  else:
    return "neutral"

In [65]:
df['Sentiment'] = df['Data'].apply(get_sentiment)
sentiment_counts = df['Sentiment'].value_counts()
print("Sentiment distribution:\n", sentiment_counts)

Sentiment distribution:
 Sentiment
neutral     1081
positive     782
negative     137
Name: count, dtype: int64

In [66]:
# Sentiment by category
sentiment_by_category = df.groupby('Labels')['Sentiment'].value_counts().unstack(fill_value=0)
print("Sentiment by category:\n", sentiment_by_category)

Sentiment by category:
 Sentiment                 negative  neutral  positive
Labels
alt.atheism                      5       60        35
comp.graphics                   10       51        39
comp.os.ms-windows.misc          9       48        43
comp.sys.ibm.pc.hardware         6       49        45
comp.sys.mac.hardware            7       50        43
comp.windows.x                  10       53        37
misc.forsale                     7       33        60
rec.autos                        7       48        45
rec.motorcycles                  7       49        44
rec.sport.baseball               8       53        39
rec.sport.hockey                13       56        31
sci.crypt                        3       62        35
sci.electronics                  4       56        40
sci.med                         11       56        33
sci.space                        5       53        42
soc.religion.christian           1       61        38
talk.politics.guns               8       60        32
talk.politics.mideast            7       68        25
talk.politics.misc               4       65        31
talk.religion.misc               5       50        45

In [69]:
# Sample Inspection

In [70]:
print(df[['Data','Labels','Sentiment']].sample(5))

                                                   Data  \
1277  Path: cantaloupe.srv.cs.cmu.edu!rochester!udel...
883   Newsgroups: rec.motorcycles\nPath: cantaloupe....
1484  Xref: cantaloupe.srv.cs.cmu.edu sci.space:6148...
391   Newsgroups: comp.sys.ibm.pc.hardware\nPath: ca...
168   Path: cantaloupe.srv.cs.cmu.edu!das-news.harva...

                        Labels Sentiment
1277           sci.electronics  positive
883            rec.motorcycles  positive
1484                 sci.space  positive
391   comp.sys.ibm.pc.hardware  positive
168              comp.graphics   neutral